# .pre-commit-hooks.yaml
- id: maven-nyx-version-sync
  name: Ensure Maven version matches Nyx and Liquibase files exist
  description: |
    Validates that:
    - The version in pom.xml matches the version from Nyx (via JSON)
    - Required Liquibase files (<version>.sql and <version>_rollback.sql) exist
  entry: check-version-sync
  language: python
  pass_filenames: false
  require_serial: true
  always_run: true
  stages: [pre-commit, pre-push]